CREATE TABLE categoria
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255)                            NOT NULL,
    descricao TEXT                                    NOT NULL,
    CONSTRAINT pk_categoria PRIMARY KEY (id)
);