CREATE TABLE produto
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(255)                            NOT NULL,
    descricao    TEXT                                    NOT NULL,
    preco        DECIMAL                                 NOT NULL,
    ativo        BOOLEAN                                 NOT NULL,
    categoria_id BIGINT,
    CONSTRAINT pk_produto PRIMARY KEY (id)
);

ALTER TABLE produto
    ADD CONSTRAINT FK_PRODUTO_ON_CATEGORIA FOREIGN KEY (categoria_id) REFERENCES categoria (id);